# Generated by Django 6.0.2 on 2026-03-03 05:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Paper',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='QuestionType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Concept',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('paper', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='concepts', to='exam.paper')),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.TextField()),
                ('data', models.JSONField()),
                ('correct_answer', models.CharField(max_length=200)),
                ('concept', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exam.concept')),
                ('paper', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exam.paper')),
                ('question_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exam.questiontype')),
            ],
        ),
    ]
