# Generated by Django 6.0.2 on 2026-03-03 05:54

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='data',
            new_name='question_data',
        ),
        migrations.AddField(
            model_name='question',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2026, 3, 3, 5, 53, 19, 500813, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='question',
            name='questionttpw',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='exam.questiontype'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='question',
            name='question_type',
            field=models.CharField(choices=[('MCQ', 'MCQ'), ('MATCH', 'Match the Following'), ('MULTI', 'Multiple Statement'), ('CORRECT_INCORRECT', 'Correct / Incorrect'), ('PAIR', 'Correct / Incorrect Pair'), ('ASSERTION_REASON', 'Assertion Reason'), ('ARRANGE', 'Arrange the Following'), ('TRUE_FALSE_PATTERN', 'True or Not Pattern'), ('WHICH_AMONG', 'Which Among')], max_length=30),
        ),
    ]
