# Generated by Django 6.0.2 on 2026-03-03 06:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0002_rename_data_question_question_data_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='questionttpw',
            new_name='questiontype',
        ),
    ]
