# Generated by Django 6.0.2 on 2026-03-04 15:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0003_rename_questionttpw_question_questiontype'),
    ]

    operations = [
        migrations.AddField(
            model_name='concept',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='exam.concept'),
        ),
    ]
