# Generated by Django 6.0.2 on 2026-03-04 16:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0005_question_parent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='concept',
            name='parent',
        ),
        migrations.RemoveField(
            model_name='question',
            name='parent',
        ),
    ]
