# Generated by Django 6.0.2 on 2026-04-18 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0006_remove_concept_parent_remove_question_parent'),
    ]

    operations = [
        migrations.AddField(
            model_name='concept',
            name='attempts',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
